substitutions:
  _IMAGE_NAME: 'dhruv-mistry-test'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'tag-for-latest'
    waitFor: ['build-image']
    args:
      - 'tag'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-tag'
    waitFor: ['tag-for-latest']
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    waitFor: ['push-tag']
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest'

  - name: 'gcr.io/cloud-builders/git'
    id: 'update-and-push-deployment'
    waitFor: ['push-latest']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euxo pipefail

        # Setup SSH
        mkdir -p /root/.ssh
        chmod 700 /root/.ssh

        # Write your SSH private key from the environment variable (assuming _GITHUB_SSH_KEY is set)
        printf "%s\n" "$_GITHUB_SSH_KEY" > /root/.ssh/id_ed25519
        chmod 600 /root/.ssh/id_ed25519

        # Add github.com to known_hosts in the right location
        ssh-keyscan github.com > /root/.ssh/known_hosts
        chmod 644 /root/.ssh/known_hosts

        # Optional: test SSH connection (for debug)
        ssh -vT git@github.com


        # Set Git identity
        git config --global user.email "cloudbuild@google.com"
        git config --global user.name "Cloud Build"

        # Modify the image tag in the manifest
        sed -i "s|^[[:space:]]*image: .*|        image: gcr.io/tony-test-gcr-forportal/dhruv-mistry-test:$BUILD_ID|" kube/deployment.yaml

        # Commit and push if changed
        if [[ -n $(git status -s) ]]; then
          git add kube/deployment.yaml
          git commit -m "Update deployment image to $BUILD_ID"
          git push git@github.com:dhruvmistry2000/test-cs.git HEAD
        else
          echo "No changes to commit"
        fi


images:
  - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
