substitutions:
  _IMAGE_NAME: 'dhruv-mistry-test'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA'
      - '.'

images:
  - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA'

options:
  logging: NONE
