substitutions:
  _IMAGE_NAME: 'dhruv-mistry-test'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$$PROJECT_ID/${_IMAGE_NAME}:$$BUILD_ID'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'tag'
      - 'gcr.io/$$PROJECT_ID/${_IMAGE_NAME}:$$BUILD_ID'
      - 'gcr.io/$$PROJECT_ID/${_IMAGE_NAME}:latest'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$$PROJECT_ID/${_IMAGE_NAME}:$$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$$PROJECT_ID/${_IMAGE_NAME}:latest'

images:
  - 'gcr.io/$$PROJECT_ID/${_IMAGE_NAME}:$$BUILD_ID'
  - 'gcr.io/$$PROJECT_ID/${_IMAGE_NAME}:latest'

options:
  logging: NONE
