substitutions:
  _IMAGE_NAME: 'dhruv-mistry-test'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'tag-for-latest'
    waitfor: ['build-image']
    args:
      - 'tag'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-tag'
    waitfor: ['tag-for-latest']
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    waitfor: ['push-tag']
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest'

  - name: 'gcr.io/cloud-builders/git'
    id: 'update-and-push-deployment'
    waitfor: ['push-latest']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i "s|^[[:space:]]*image: .*|        image: gcr.io/tony-test-gcr-forportal/dhruv-mistry-test:$BUILD_ID|" kube/deployment.yaml
        git config --global user.email "cloudbuild@google.com"
        git config --global user.name "Cloud Build"
        git add kube/deployment.yaml
        git commit -m "Update deployment image to $BUILD_ID"
        git push origin HEAD

images:
  - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest'

options:
  logging: NONE
